CREATE TABLE IF NOT EXISTS links(
  id SERIAL PRIMARY KEY,
  code VARCHAR(8) UNIQUE NOT NULL;
  target_url TEXT NOT NULL,
  click INT DEFAULT 0,
  last_clicked TIMESTAMPTZ,
  create_at TIMESTAMPTZ DEFAULT NOW();
  delete BOOLEAN DEFAULT FALSE
)